# Generated by Django 4.2.14 on 2024-08-02 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('job_title', models.CharField(max_length=255)),
                ('application_date', models.DateField()),
                ('status', models.CharField(max_length=100)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
